# -*- coding: utf-8 -*-
"""4IF ML 2026 - Classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ZWqWnEeYxJL2MR18xz31qGA9RCu1yvt
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

if4_ml_2026_classification_path = kagglehub.competition_download('4-if-ml-2026-classification')

print('Data source import complete.')

import numpy as np # for linear algebra
import pandas as pd # for data processing, CSV file I/O (e.g. pd.read_csv)

# import des modèles
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df = pd.read_csv("/root/.cache/kagglehub/competitions/4-if-ml-2026-classification/train.csv")
df = df.dropna() # pour supprimer les nulls

X = df.drop(columns=["anomaly_label", "id"])  # l'id est inutile et on le supprime pour ne pas avoir de l'influence dans le modèle
y = df["anomaly_label"]

# Dummies
# Elle permettent d'ecoder les données
# --> On transforme les données non numériques (ex Adult, Elderly, Pediatric) en données numériques (ex 0, 1, 2)
X = pd.get_dummies(X)

# Normalisation
# La normalisation transforme les variables numériques pour qu’elles aient des échelles comparables.
# par exemple les valeurs de 0 à 1000 et 0 à 10 seront toutes les deux ramenées à des valeurs entre 0 et 1 pour contribuer équitablement
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


# séparation des données test / train
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42 # les données de test = 20% des données d'entrainement
)

models = [
    LogisticRegression(max_iter=1000, random_state=42),
    KNeighborsClassifier(),
    RandomForestClassifier(random_state=42),
    SVC(random_state=42),
    GradientBoostingClassifier(random_state=42)
]

performance_metrics = []

for model in models:

  # Entrainement du modèle
  model.fit(X_train, y_train)

  # Prédictions : maintenant que le modèle est entrainé, on va pouvoir le tester sur les données de test
  y_pred = model.predict(X_test)

  # Evaluation : on va comparer la prédiction du modèle avec le vrai label des données
  accuracy = accuracy_score(y_test, y_pred)

  # Store metrics in a dictionary
  metrics_dict = {
      'Model': model.__class__.__name__,
      'Accuracy': accuracy
  }
  performance_metrics.append(metrics_dict)

metrics_df = pd.DataFrame(performance_metrics)
print("Performance Metrics for Each Model:")
print(metrics_df)

# visualisation (facultatif... C'est juste pour faire beau)
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 6))  # crée la figure directement

# Trace le barplot
sns.barplot(x='Model', y='Accuracy', data=metrics_df)

# Titres et labels
plt.title('Comparaison des Accuracy des modèles')
plt.ylabel('Accuracy')
plt.xlabel('Modèle')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# prendre le modèle avec le meilleur résultat, et l'utiliser pour générer les labels du fichier test.csv
best_model_name = metrics_df.loc[metrics_df['Accuracy'].idxmax()]['Model']

best_model = None
for model in models:
    if model.__class__.__name__ == best_model_name:
        best_model = model
        break

print(f"The best model based on F1-Score is: {best_model_name}")

import os
test_file_path = os.path.join(if4_ml_2026_classification_path, 'test.csv')
test_df = pd.read_csv(test_file_path)

test_ids = test_df['id']
X_test_processed = test_df.drop(columns=["id"])
X_test_processed = pd.get_dummies(X_test_processed)

# Align columns with the training data (X) to handle potential missing columns in test set
# This ensures that the test set has the same feature columns as the training set
# Fill new columns with 0 and drop columns not in the training set
X_test_aligned = X_test_processed.reindex(columns=X.columns, fill_value=0)

# Scale the test features using the already fitted scaler
X_test_scaled_for_prediction = scaler.transform(X_test_aligned)
test_predictions = best_model.predict(X_test_scaled_for_prediction)
submission_df = pd.DataFrame({'id': test_ids, 'anomaly_label': test_predictions})
submission_df.to_csv('submission.csv', index=False)


from google.colab import files
files.download('/content/submission.csv')